$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - .git/{FETCH_HEAD,HEAD,index,packed-refs,config}
  - .git/*/*/**
  - .git/**/*.sample
  - .gitattributes
  - .gitignore
  - .prettierignore
  - .vscode
  - '*-lock.*'
  - '*.lock'
  - /coverage
  - /dist
  - __snapshots__
  - CHANGELOG.md
  - cspell.config.*
  - node_modules
enableGlobDot: true
useGitignore: true
dictionaryDefinitions: []
dictionaries: []
words:
  - autobuild
  - buildscript
  - codecov
  - codeql
  - coverallsapp
  - lcov
  - pnpm
  - vitest
ignoreWords: []
import: []
